import "./globals.landing.css";

import { Inter, Sora } from "next/font/google";
import type { Metadata } from "next";
import Header from "@/components/landing/header";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const sora = Sora({ subsets: ["latin"], variable: "--font-sora" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${sora.variable} bg-gray-950 font-inter text-base text-gray-200 antialiased`}>
                <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    );
}
